swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - https
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/{notes}:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions Update
      description: API for updating user Transactions
      parameters:
        - in: path
          name: notes
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update Transactions notes
          required: true
          schema:
            $ref: '#/definitions/UserTransactions'
      produces:
        - application/json
      responses:
        '200':
          description: Transactions note updated successfully
          schema:
            $ref: '#/definitions/UserTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User Transactions Category
      description: API for updating Transactions Category
      parameters:
        - in: body
          name: body
          description: Update Transactions Category
          required: true
          schema:
            $ref: '#/definitions/TransactionsCategory'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction Category updated successfully
          schema:
            $ref: '#/definitions/TransactionsCategory'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/months:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Every Month Transaction
      description: API for displaying every month transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Display Transactions of every month
          required: true
          schema:
            $ref: '#/definitions/MonthsTransactions'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction Category displayed successfully
          schema:
            $ref: '#/definitions/MonthsTransactions'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions/details:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions details
      description: API for displaying Transactions Details
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Display a chosen transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionRequest'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction Details displayed successfully
          schema:
            $ref: '#/definitions/TransactionsDetails'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    type: object
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  UserTransactions:
    type: object
    properties:
      transactionId:
        type: string
      notes: 
        type: string
  TransactionsCategory:
    type: object
    properties:
      transactionId:
        type: string
      category:
        type: string
  MonthsTransactions:
    type: object
    properties:
      CurrentMonth:
        type: array
        items:
          type: object
          properties:
            date:
              type: integer
              format: int32
            description : 
              type : string
            amount:
              type: number
              format: float
            balance:
              type: number
              format: float 
            accountNumber : 
              type : number
  TransactionRequest :
    type : object 
    properties : 
      transactionId:
        type: string
  TransactionsDetails:
    type: object
    properties:
      transactions:
        type: array
        items:
          type: object
          properties:
            date:
              type: string
            description:
              type: string
            amount:
              type: number
              format: float
            balance:
              type: number
              format: float 
            category:
              type: string
            transactionId:
              type: string
            notes:
              type: string